language: node_js
node_js: stable
addons:
  chrome: stable
script:
- npm test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test:sl; fi
env:
  global:
    - secure: >-
        M56hPQ3z2NfjYbF6Jlb/bQHh1+kXi+RgrAQ6V1Jlq6teFaYt3Ug7owghNXg+zzKTpJFlkJWmIsqGw2bFeBWSC+2boByamZ3k450eMIAy99bRkVuB0RnFfYhnDCvCBT0R7hxCt31qvPxyH3PS+MkwBmNGpbb5vo8SQNNGKzL/gwk+wguFOSpHyViVUfWHJr5SQDnHtn3qTrxPzp6Bu5kEhGTP4Qhx/j0ZcaAvfifw7hgOmJfJ1/a7pKTA3JXakYgWEY4HI8djqWrVNvpoOra4HHGnMWv0TWVJDoQqhypxPPrSMMMCjElJ57KBNf3TshGMqRNOUZUIc6uXlcUVJnxyTL1IVjKe7zwIiF3gCbqEGKpfGdZ1SGmYozz8BWOdCsEgnHeZXPPDBxH8tzMpt5Q9oGn5KL4peHx875DA5zY2knQTag27qRG37KmKZqHyRDuKUw9W6r2Lq86OTFaqXA1tVXVqXzf7wMydCLxWDUDevQYvTp8d/wBRIIDgROeid0RxiS/bhr7bMpQYfwC+e6ewpv/2m6TZQTVcvs/7gogOxQtNYD0J1kHcwP7lAOAfr2IyvZlAW8Ddzzi0m/gFQDdxUOYea3FM8pIJBzFMF6nL5AsyUvoT0K3hSdw/Bv/wLSAmg0Jkcy/B6vZZ3Nt0bnzyPsFBNIspyoFilC7KIwX3YWA=
    - secure: >-
        fzROjYOEL3WP2gGribfQbBSt+X6sakUX2nDZjuXOddH6Ed4qLmXGihGaGJB3TbelRbtwCWsTQYYBqaCZNT0fY10S2OcBnzd/ll79JwDodhWf/T9XNDzmQHTY9yBVSs97slZGYwNMNW826n5yD0RB1G5xKQsIVmk3TDRwetS7UqXw4+3Bksv7iAHuqIlTr4pSr1P9hdBUMxa6tf54aFCm6KtkqXyUs534U9JHSZ+jFOFbIe167WS+RAmH7j6RY6SvRL3H1/C0eGYcGbVrfCuEY3x85qlam+qwc/4a4eDrxmkKrjoAajgVDYd0PWCKM4ENg4AvjTcw9MDH64Q01tU6WJWbe/0oa1gxwDKgOPtyU1lOvVkWWlyOHZzRt1ut1J+mvfNBlsMBKMt2iMzl1bwuc2/Vv60mRoXiOvhSHWlkuFqz7/8+pxjtnRLyMplb0sUiZB12k8FreHnahyoN35ZqhuDuCBtpopF0eN1hsbfzFSFh295D2a0dcjX6QiMtJEMn0C2MsQnLE16jcSYwmDy7kQ+x8A+2JDNg28oP3wK/5ufzZo85Vj2qp2d0mcXcd91HkF9jCSOe1MClMaooWupKJLU6SaImCzgPG5PKYLNGbYJIjOubC1MCupuU2gIOcnk5AcIr7ST+ZVodQfyMNFElrZhLmA0QGjrmYc3WehQvvds=
